@extends('layouts.app')
@section('title',$canViewAll?'Tổng quan chỉ tiêu & dữ liệu':'Chỉ tiêu & dữ liệu cá nhân')
@section('header','Chỉ tiêu & dữ liệu')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><h1 class="page-title">{{$canViewAll?'Tổng quan chỉ tiêu & dữ liệu':'Chỉ tiêu & dữ liệu cá nhân'}}</h1><div class="page-subtitle">Theo dõi KPI cộng dồn {{$canViewAll?'trên toàn hệ thống':'của account đang đăng nhập'}} năm {{ $year }}.</div></div>
    <form class="d-flex gap-2"><input class="form-control" type="number" name="year" value="{{ $year }}" min="2020" max="2100" style="width:120px"><button class="btn btn-primary"><i class="bi bi-filter"></i></button></form>
</div>
<div class="row g-3 mb-4">
    @foreach([['Chỉ tiêu năm',$totals['target_quantity'],'primary','bi-bullseye','kpis.index','kpis'],['Đã thực hiện',$totals['actual_quantity'],'success','bi-check2-circle','imports.records','imports'],['Còn lại',$totals['remaining_quantity'],'warning','bi-hourglass-split','reports.index','reports'],['Vượt chỉ tiêu',$totals['excess_quantity'],'danger','bi-graph-up-arrow','payments.index','payments']] as [$label,$value,$color,$icon,$route,$permission])
    <div class="col-sm-6 col-xl-3">@if(auth()->user()->allowed($permission))<a class="dashboard-card-link" href="{{route($route,['year'=>$year])}}">@endif<div class="card card-soft stat-card h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="stat-label">{{$label}}</div><div class="stat-value text-{{$color}}">{{number_format($value,2)}}</div></div><div class="stat-icon bg-{{$color}}-subtle text-{{$color}}"><i class="bi {{$icon}}"></i></div></div>@if($label==='Vượt chỉ tiêu')<div class="small text-muted mt-2">Dự kiến: {{number_format($totals['payment_amount'])}}đ</div>@endif</div></div>@if(auth()->user()->allowed($permission))</a>@endif</div>
    @endforeach
</div>
<div class="row g-4 mb-4">
    <div class="col-xl-8"><div class="card card-soft h-100"><div class="card-header bg-white border-0 p-4 pb-2"><h5 class="mb-1">Tiến độ theo tháng</h5><small class="text-muted">Tỷ lệ thực hiện so với chỉ tiêu từng tháng.</small></div><div class="card-body px-4 pb-4">
        @for($m=1;$m<=12;$m++)
            @php($month=$monthly[$m]) @php($pct=$month['target_quantity']>0?min(100,round($month['actual_quantity']/$month['target_quantity']*100)):0)
            <div class="d-flex align-items-center gap-3 mb-3"><div class="small fw-semibold" style="width:65px">Tháng {{ $m }}</div><div class="timeline-month flex-grow-1"><span style="width:{{ $pct }}%"></span></div><div class="small text-muted" style="width:115px;text-align:right">{{ number_format($month['actual_quantity'],1) }}/{{ number_format($month['target_quantity'],1) }}</div></div>
        @endfor
    </div></div></div>
    <div class="col-xl-4"><div class="card card-soft h-100"><div class="card-header bg-white border-0 p-4 pb-2"><h5 class="mb-1">Cơ cấu năm {{ $year }}</h5><small class="text-muted">4 quý và 12 tháng.</small></div><div class="card-body p-4"><div class="period-tree">@for($q=1;$q<=4;$q++)<div class="quarter-box"><strong>Quý {{ $q }}</strong>@for($m=(($q-1)*3+1);$m<=($q*3);$m++)<span class="month-chip">T{{ $m }}</span>@endfor</div>@endfor</div>@if($user->isLeader())<hr><div class="row text-center"><div class="col"><strong class="d-block fs-4">{{ $personnelCount }}</strong><small class="text-muted">Nhân sự</small></div><div class="col"><strong class="d-block fs-4">{{ $collaboratorCount }}</strong><small class="text-muted">CTV</small></div><div class="col"><strong class="d-block fs-4">{{ $userCount }}</strong><small class="text-muted">Tài khoản</small></div></div>@endif</div></div></div>
</div>
<div class="card card-soft"><div class="card-header bg-white border-0 p-4 d-flex justify-content-between align-items-center"><div><h5 class="mb-1">Chi tiết chỉ tiêu năm</h5><small class="text-muted">Kết quả đã quy đổi theo từng khóa học.</small></div>@if(auth()->user()->allowed('reports'))<a class="btn btn-outline-primary" href="{{ route('reports.index',['year'=>$year]) }}">Xem báo cáo</a>@endif</div><div class="table-responsive"><table class="table table-modern"><thead><tr><th>Nhân sự</th><th>Khóa học</th><th>Chỉ tiêu</th><th>Thực hiện</th><th>Còn lại</th><th>Vượt</th><th>Tiến độ</th><th>Trạng thái</th></tr></thead><tbody>@forelse($rows->take(12) as $row)<tr><td><strong>{{ $row['personnel_name'] }}</strong><div class="small text-muted">{{ $row['personnel_type_label'] }}</div></td><td>{{ $row['course_name'] }}</td><td>{{ number_format($row['target_quantity'],2) }}</td><td>{{ number_format($row['actual_quantity'],2) }}</td><td>{{ number_format($row['remaining_quantity'],2) }}</td><td class="fw-bold text-danger">{{ number_format($row['excess_quantity'],2) }}</td><td style="min-width:150px"><div class="d-flex justify-content-between small mb-1"><span>{{ number_format($row['completion_pct'],1) }}%</span></div><div class="progress"><div class="progress-bar" style="width:{{ min(100,$row['completion_pct']) }}%"></div></div></td><td>@if($row['status']==='exceeded')<span class="badge-soft badge-danger">Vượt chỉ tiêu</span>@elseif($row['status']==='completed')<span class="badge-soft badge-success">Đã đạt</span>@elseif($row['status']==='not_completed')<span class="badge-soft badge-warning">Chưa đạt</span>@else<span class="badge-soft badge-gray">Chưa giao</span>@endif</td></tr>@empty<tr><td colspan="8"><div class="empty-state"><i class="bi bi-inbox fs-1"></i><p class="mt-2">Chưa có dữ liệu chỉ tiêu.</p></div></td></tr>@endforelse</tbody></table></div></div>
@endsection
