@extends('layouts.app')
@section('title','Hướng dẫn sử dụng')
@section('header','Hướng dẫn sử dụng')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><h1 class="page-title">Hướng dẫn sử dụng {{ $systemName }}</h1><div class="page-subtitle">Hướng dẫn chi tiết theo từng quy trình nghiệp vụ trong hệ thống.</div></div>
    <a class="btn btn-primary" href="{{ route('welcome') }}"><i class="bi bi-house-door me-2"></i>Về trang chào mừng</a>
</div>
<div class="guide-layout">
<aside class="card card-soft guide-nav"><div class="card-body"><strong>Mục lục hướng dẫn</strong>
<a href="#dang-nhap"><i class="bi bi-box-arrow-in-right"></i>Đăng nhập & tài khoản</a><a href="#giao-dien"><i class="bi bi-layout-sidebar"></i>Giao diện & menu</a><a href="#ke-hoach"><i class="bi bi-calendar2-check"></i>Kế hoạch & nhắc việc</a><a href="#tu-van"><i class="bi bi-headset"></i>Tư vấn & tuyển sinh</a><a href="#hoc-vien"><i class="bi bi-mortarboard"></i>Học viên & lớp học</a><a href="#hoc-phi"><i class="bi bi-receipt"></i>Học phí & phiếu thu</a><a href="#kpi"><i class="bi bi-bullseye"></i>KPI & báo cáo</a><a href="#quan-tri"><i class="bi bi-shield-lock"></i>Quản trị hệ thống</a><a href="#xu-ly-loi"><i class="bi bi-tools"></i>Lỗi thường gặp</a>
</div></aside>
<div class="guide-content">
<section id="dang-nhap" class="card card-soft guide-section"><span>01</span><div><h4>Đăng nhập và quản lý tài khoản</h4><ol class="guide-steps"><li><strong>Đăng nhập:</strong> nhập email và mật khẩu được quản trị viên cấp rồi nhấn “Đăng nhập”.</li><li><strong>Đổi mật khẩu:</strong> mở menu tài khoản góc phải, chọn “Đổi mật khẩu”, nhập mật khẩu hiện tại và mật khẩu mới.</li><li><strong>Cập nhật hồ sơ:</strong> chọn “Hồ sơ cá nhân” để sửa họ tên, email và số điện thoại.</li><li><strong>Đăng xuất:</strong> chọn “Đăng xuất” trước khi rời máy dùng chung.</li></ol><div class="guide-note"><i class="bi bi-shield-check"></i><span>Không chia sẻ mật khẩu. Nếu tài khoản bị khóa hoặc quên mật khẩu, liên hệ quản trị viên.</span></div></div></section>
<section id="giao-dien" class="card card-soft guide-section"><span>02</span><div><h4>Làm quen với giao diện</h4><ul><li><strong>Menu bên trái:</strong> chứa các phân hệ được cấp quyền; menu mỗi tài khoản có thể khác nhau.</li><li><strong>Topbar:</strong> hiển thị vị trí trang, chuông nhắc việc và tài khoản đang dùng.</li><li><strong>Nút thao tác:</strong> đưa chuột lên icon để xem tên chức năng.</li><li><strong>Tìm kiếm:</strong> nhập từ khóa, chọn điều kiện rồi lọc; xóa điều kiện để xem toàn bộ.</li><li><strong>Điện thoại:</strong> nhấn biểu tượng ba gạch để mở hoặc đóng menu.</li></ul></div></section>
<section id="ke-hoach" class="card card-soft guide-section"><span>03</span><div><h4>Kế hoạch, lịch và nhắc việc</h4><ol class="guide-steps"><li>Mở “Kế hoạch & lịch”.</li><li>Nhập tên, ngày giờ, ưu tiên và ghi chú cần chuẩn bị.</li><li>Chọn nhắc đúng ngày hoặc trước 1–30 ngày rồi lưu.</li><li>Dùng mũi tên trên lịch để chuyển tháng; nhấn kế hoạch để xem chi tiết.</li><li>Đánh dấu hoàn thành, mở lại hoặc xóa khi cần.</li></ol><p class="mt-3"><strong>Chuông thông báo:</strong> số đỏ là việc đang đến hạn nhắc. Việc quá hạn tiếp tục cảnh báo đến khi hoàn thành.</p></div></section>
<section id="tu-van" class="card card-soft guide-section"><span>04</span><div><h4>Tư vấn và tuyển sinh</h4><ol class="guide-steps"><li>Vào “Học viên tiềm năng”, chọn thêm mới và nhập thông tin liên hệ, nhu cầu học.</li><li>Cập nhật quá trình chăm sóc trong “Công việc tư vấn”.</li><li>Khi khách đăng ký, dùng chức năng chuyển đổi để tạo học viên chính thức.</li><li>Kiểm tra trùng số điện thoại hoặc email trước khi tạo mới.</li></ol></div></section>
<section id="hoc-vien" class="card card-soft guide-section"><span>05</span><div><h4>Học viên, chương trình và lớp học</h4><ul><li><strong>Học viên:</strong> quản lý thông tin cá nhân, người giám hộ và liên hệ.</li><li><strong>Chương trình:</strong> thiết lập lộ trình và cấp độ đào tạo.</li><li><strong>Khóa học:</strong> khai báo giáo trình, học phí, thời lượng và số buổi.</li><li><strong>Lớp học:</strong> tạo lớp, chọn khóa học, lịch học và xếp học viên.</li></ul><div class="guide-note"><i class="bi bi-info-circle-fill"></i><span>Không xóa chương trình đang sử dụng; nên chuyển sang trạng thái ngừng hoạt động để giữ lịch sử.</span></div></div></section>
<section id="hoc-phi" class="card card-soft guide-section"><span>06</span><div><h4>Thu học phí và in phiếu thu</h4><ol class="guide-steps"><li>Mở “Thu học phí”, chọn học viên và tạo khoản phải thu.</li><li>Kiểm tra học phí, miễn giảm, số đã thu và công nợ.</li><li>Nhập số tiền, ngày thu và phương thức thanh toán.</li><li>Nếu chưa có số phiếu, xác nhận đóng trước và bổ sung sau.</li><li>Sau xác nhận, chọn xem, in hoặc lưu PDF A5 ngang.</li></ol><div class="guide-note"><i class="bi bi-exclamation-triangle-fill"></i><span>Kiểm tra đúng học viên và số tiền trước khi xác nhận; cho phép trình duyệt mở cửa sổ in và tải tệp.</span></div></div></section>
<section id="kpi" class="card card-soft guide-section"><span>07</span><div><h4>KPI, nhập dữ liệu và báo cáo</h4><ul><li>Tạo kế hoạch KPI đúng năm và giao chỉ tiêu cho nhân sự.</li><li>Chọn kỳ theo thứ tự <strong>Năm → Quý → Tháng</strong>; hệ thống cộng dồn theo kỳ.</li><li>Dùng đúng tệp Excel mẫu, không đổi tên các cột bắt buộc.</li><li>Kiểm tra danh sách lỗi sau nhập và sửa các dòng không hợp lệ.</li><li>Áp dụng bộ lọc trước khi xuất báo cáo Excel.</li></ul></div></section>
<section id="quan-tri" class="card card-soft guide-section"><span>08</span><div><h4>Quản trị và cấu hình</h4><ul><li><strong>Nhân sự:</strong> hồ sơ, chức vụ và trạng thái hoạt động.</li><li><strong>Tài khoản:</strong> tạo người dùng, liên kết nhân sự, khóa hoặc đặt lại mật khẩu.</li><li><strong>Vai trò & quyền:</strong> cấp quyền xem, thêm, sửa, xóa và xuất dữ liệu.</li><li><strong>Cấu hình:</strong> đổi tên phần mềm, logo, màu và kiểu tải trang.</li><li><strong>Nhật ký:</strong> kiểm tra lịch sử đăng nhập và thao tác quản trị.</li></ul><div class="guide-note"><i class="bi bi-shield-lock-fill"></i><span>Chỉ cấp đúng quyền cần thiết, đặc biệt với quyền xóa và quản trị tài khoản.</span></div></div></section>
<section id="xu-ly-loi" class="card card-soft guide-section"><span>09</span><div><h4>Xử lý lỗi thường gặp</h4><div class="guide-faq"><details><summary>Giao diện chưa cập nhật</summary><p>Nhấn Ctrl + F5. Trên điện thoại, đóng tab rồi mở lại.</p></details><details><summary>In hoặc tải PDF chạy lâu</summary><p>Kiểm tra trình duyệt có chặn cửa sổ bật lên hoặc tải xuống; không nhấn nhiều lần.</p></details><details><summary>Không thấy chức năng trong menu</summary><p>Tài khoản chưa được cấp quyền; liên hệ quản trị viên kiểm tra Vai trò & quyền.</p></details><details><summary>Số liệu báo cáo chưa đúng kỳ</summary><p>Xóa bộ lọc cũ và chọn lại theo thứ tự Năm → Quý → Tháng.</p></details><details><summary>Không nhận nhắc kế hoạch</summary><p>Kiểm tra trạng thái hoàn thành, ngày giờ và số ngày nhắc trước. Chuông cập nhật khi mở hoặc chuyển trang.</p></details></div></div></section>
</div></div>
@endsection
