@extends('layouts.app')
@section('title','Lập khoản thu học phí') @section('header','Quản lý học viên')
@section('content')
<div class="d-flex justify-content-between mb-4"><div><h1 class="page-title">Lập khoản thu học phí</h1><div class="page-subtitle">Chọn đúng học viên trong lớp; khóa học và học phí được lấy tự động từ lớp.</div></div><a class="btn btn-light" href="{{route('language-tuition.index')}}">Quay lại</a></div>
<div class="card card-soft form-card"><div class="card-header"><h5>Thông tin khoản thu</h5></div><div class="card-body p-4"><form method="POST" action="{{route('language-tuition.store')}}">@csrf
<div class="row g-3">
<div class="col-12"><label class="form-label">Học viên – Lớp – Khóa học</label><select class="form-select" data-enrollment-choice required><option value="">Chọn học viên trong lớp chưa có phiếu thu</option>@foreach($enrollments as $enrollment)<option value="{{$enrollment->id}}" data-student="{{$enrollment->language_student_id}}" data-class="{{$enrollment->language_class_id}}" data-course="{{$enrollment->languageClass?->language_course_id}}" @selected((old('language_student_id',$selectedStudent)==$enrollment->language_student_id)&&(old('language_class_id',$selectedClass)==$enrollment->language_class_id))>{{$enrollment->student?->code}} – {{$enrollment->student?->name}} · Lớp {{$enrollment->languageClass?->code}} – {{$enrollment->languageClass?->name}} · Khóa {{$enrollment->languageClass?->course?->name}} · Học phí lớp {{number_format($enrollment->languageClass?->default_tuition??0)}}đ</option>@endforeach</select>
<input type="hidden" name="language_student_id" value="{{old('language_student_id',$selectedStudent)}}"><input type="hidden" name="language_class_id" value="{{old('language_class_id',$selectedClass)}}"><input type="hidden" name="language_course_id" value="{{old('language_course_id')}}"><div class="form-text">Một học viên học hai lớp sẽ có hai dòng riêng. Mỗi dòng chỉ lập phiếu một lần.</div></div>
<div class="col-md-6"><label class="form-label">Khách hàng nguồn</label><select class="form-select" name="language_lead_id"><option value="">Không liên kết</option>@foreach($leads as $lead)<option value="{{$lead->id}}" @selected(old('language_lead_id',$selectedLead)==$lead->id)>{{$lead->code}} – {{$lead->name}}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Miễn giảm riêng của học viên</label><select class="form-select" name="language_discount_policy_id"><option value="">Dùng mức riêng đã lưu của học viên</option>@foreach($discounts as $discount)<option value="{{$discount->id}}">{{$discount->name}} – giảm {{\App\Support\ValueFormatter::percentage($discount->percentage)}}%</option>@endforeach</select><div class="form-text">Hệ thống sẽ so sánh với miễn giảm của lớp và chỉ áp dụng mức cao hơn, không cộng dồn.</div></div>
<div class="col-md-4"><label class="form-label">Hạn đóng</label><input class="form-control" type="date" name="due_date" value="{{old('due_date')}}"></div>
<div class="col-12"><label class="form-label">Ghi chú</label><textarea class="form-control" name="note">{{old('note')}}</textarea></div>
</div><div class="form-actions"><a class="btn btn-light" href="{{route('language-tuition.index')}}">Hủy</a><button class="btn btn-primary"><i class="bi bi-receipt me-2"></i>Lập khoản thu</button></div>
</form></div></div>
@endsection
@push('scripts')<script>{const choice=document.querySelector('[data-enrollment-choice]'),student=document.querySelector('[name="language_student_id"]'),classInput=document.querySelector('[name="language_class_id"]'),course=document.querySelector('[name="language_course_id"]');const sync=()=>{const option=choice.options[choice.selectedIndex];student.value=option?.dataset.student||'';classInput.value=option?.dataset.class||'';course.value=option?.dataset.course||''};choice.addEventListener('change',sync);sync()}</script>@endpush
