@extends('layouts.app')
@section('title','Thu học phí') @section('header','Quản lý học viên') @section('content')
@php($labels=['unpaid'=>'Chưa đóng','partial'=>'Đóng một phần','pending_receipt'=>'Chờ bổ sung phiếu thu','paid'=>'Đã đóng đủ','transferred'=>'Đã quyết toán chuyển lớp'])
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="page-title">Thu học phí</h1><div class="page-subtitle">Danh sách khoản phải thu của từng học viên/lớp. Nhấn Chi tiết để ghi nhận tiền.</div></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{route('language-tuition.monthly')}}"><i class="bi bi-calendar2-check me-2"></i>Theo tháng</a><a class="btn btn-outline-success" href="{{route('language-tuition.export',request()->query())}}"><i class="bi bi-file-earmark-excel me-2"></i>Excel</a><a class="btn btn-primary" href="{{route('language-tuition.create')}}"><i class="bi bi-plus-circle me-2"></i>Lập khoản thu</a></div></div>
<form class="filter-panel row g-3 mb-4"><div class="col-lg-3"><input class="form-control" name="q" value="{{request('q')}}" placeholder="Mã khoản thu hoặc học viên"></div><div class="col-lg-2"><select class="form-select" name="status"><option value="">Mọi trạng thái</option>@foreach($labels as $key=>$label)<option value="{{$key}}" @selected(request('status')===$key)>{{$label}}</option>@endforeach</select></div><div class="col-lg-2"><input class="form-control" type="number" name="year" value="{{$filterYear}}" min="2020" max="2100" aria-label="Năm"></div><div class="col-lg-2"><select class="form-select" name="quarter"><option value="">Mọi quý</option>@for($q=1;$q<=4;$q++)<option value="{{$q}}" @selected(request('quarter')==$q)>Quý {{$q}}</option>@endfor</select></div><div class="col-lg-2"><select class="form-select" name="month"><option value="">Mọi tháng</option>@for($m=1;$m<=12;$m++)<option value="{{$m}}" @selected(request('month')==$m)>Tháng {{$m}}</option>@endfor</select></div><div class="col-lg-1"><button class="btn btn-dark w-100"><i class="bi bi-filter"></i></button></div></form>
<div class="card card-soft"><div class="table-responsive"><table class="table table-modern align-middle"><thead><tr><th>Mã khoản thu</th><th>Học viên</th><th>Khóa học / lớp</th><th>Phải thu</th><th>Đã thu</th><th>Chuyển sang</th><th>Còn lại</th><th>Trạng thái</th><th></th></tr></thead><tbody>
@forelse($items as $item) @php($remaining=$item->remainingAmount())<tr><td><strong>{{$item->code}}</strong><div class="small text-muted">{{$item->created_at?->format('d/m/Y')}}</div></td><td><strong>{{$item->student->name}}</strong><div class="small text-muted">{{$item->student->code}}</div></td><td>{{$item->course->name}}<div class="small text-muted">Lớp: {{$item->languageClass?->code?:'Chưa xếp'}}</div></td><td>{{number_format($item->payable_amount)}}đ</td><td class="fw-semibold text-success">{{number_format($item->paid_amount)}}đ</td><td class="fw-semibold text-primary">{{number_format($item->credit_amount)}}đ</td><td class="fw-semibold {{$remaining>0?'text-danger':'text-muted'}}">{{number_format($remaining)}}đ</td><td><span class="badge-soft {{in_array($item->status,['paid','transferred'])?'badge-success':(in_array($item->status,['partial','pending_receipt'])?'badge-warning':'badge-danger')}}">{{$labels[$item->status]??$item->status}}</span></td><td class="text-end"><a class="btn btn-sm btn-primary text-nowrap" href="{{route('language-tuition.show',$item)}}"><i class="bi bi-eye me-1"></i>Chi tiết</a></td></tr>
@empty<tr><td colspan="9"><div class="empty-state">Không có khoản thu trong kỳ đã chọn.</div></td></tr>@endforelse
</tbody></table></div><div class="card-footer bg-white border-0">{{$items->links()}}</div></div>
@endsection
