<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phiếu thu {{ $payment->receipt_code }}</title><style>
@page{size:A5 landscape;margin:5mm}*{box-sizing:border-box}body{margin:0;color:#111;font-family:"DejaVu Sans",Arial,sans-serif;font-size:8.7px;line-height:1.25}.receipt{width:100%;max-width:200mm;margin:0 auto;background:#fff}.header{display:table;width:100%;border-bottom:1.5px solid #111;padding-bottom:4px}.header-logo,.header-info,.receipt-code{display:table-cell;vertical-align:middle}.header-logo{width:15mm}.header-logo img{width:12mm;height:12mm;object-fit:contain}.logo-default{width:12mm;height:12mm;display:table-cell;text-align:center;vertical-align:middle;border:1px solid #222;border-radius:4px;font-size:18px;font-weight:bold}.header-info strong{display:block;font-size:11px;text-transform:uppercase}.header-info span{display:block;font-size:8.5px;color:#444}.header-info .contact{margin-top:1px;color:#111;font-size:7.5px;font-weight:700}.header-info .address{color:#111;font-size:7px;font-weight:700}.receipt-code{width:31mm;text-align:right}.receipt-code strong{display:block;font-size:10px}.title{text-align:center;margin:5px 0 4px}.title h1{margin:0;font-size:17px;letter-spacing:.06em}.title p{margin:2px 0 0;font-size:9px}.info-table{width:100%;border-collapse:collapse}.info-table td{padding:1.5px 2px;vertical-align:top}.label{width:27mm;color:#444}.value{font-weight:600;border-bottom:1px dotted #777}.amount-box{margin:4px 0;padding:4px 7px;border:1.5px solid #111;border-radius:5px}.amount-line{display:table;width:100%}.amount-line span,.amount-line strong{display:table-cell}.amount-line strong{text-align:right;font-size:13px}.words{margin-top:2px;padding-top:2px;border-top:1px solid #bbb;font-style:italic}.detail{width:100%;margin-top:4px;border-collapse:collapse}.detail th,.detail td{padding:3px;border:1px solid #555;text-align:left}.detail th{background:#eee;font-size:9px}.detail td:last-child,.detail th:last-child{text-align:right}.note{min-height:12px;margin-top:4px}.signatures{display:table;width:100%;margin-top:12px;text-align:center;page-break-inside:avoid}.signature{display:table-cell;width:33.33%;padding:0 8px}.signature strong{display:block}.signature small{font-style:italic}.signature-space{height:42px}.footer{margin-top:3px;padding-top:3px;border-top:1px solid #aaa;text-align:center;color:#555;font-size:7.5px}.print-actions{position:fixed;right:16px;top:16px;display:flex;gap:8px}.print-actions a,.print-actions button{padding:9px 13px;border:0;border-radius:7px;color:#fff;background:#2563eb;text-decoration:none;font:600 12px Arial;cursor:pointer}.print-actions a{background:#16834f}@media print{.print-actions{display:none}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style></head><body>
@if(!$pdfMode)<div class="print-actions"><a data-no-loading download href="{{ route('language-tuition.receipt.pdf',$payment) }}">Tải PDF</a><button onclick="window.print()">In A5 ngang</button></div>@endif
<div class="receipt"><div class="header"><div class="header-logo">@if($logoData)<img src="{{ $logoData }}" alt="Logo">@else<span class="logo-default">E</span>@endif</div><div class="header-info"><strong>Trung tâm Ngoại ngữ và Tin học E-sky</strong><span class="contact">02903 683 888 - 0916 727 808</span><span class="address">Số 3, Đường Lê Thị Riêng, Phường Tân Thành, Tỉnh Cà Mau</span></div><div class="receipt-code"><span>Số phiếu</span><strong>{{ $payment->receipt_code ?: 'CẬP NHẬT SAU' }}</strong></div></div>
<div class="title"><h1>PHIẾU THU</h1><p>Ngày {{ $payment->paid_at?->format('d') }} tháng {{ $payment->paid_at?->format('m') }} năm {{ $payment->paid_at?->format('Y') }}</p></div>
<table class="info-table"><tr><td class="label">Họ tên người nộp:</td><td class="value">{{ $student->name }}</td></tr><tr><td class="label">Mã học viên:</td><td class="value">{{ $student->code }}</td></tr><tr><td class="label">Điện thoại:</td><td class="value">{{ $student->phone ?: '—' }}</td></tr><tr><td class="label">Địa chỉ:</td><td class="value">{{ $student->address ?: '—' }}</td></tr><tr><td class="label">Nội dung thu:</td><td class="value">Thu học phí {{ $charge->course->name }}{{ $charge->languageClass ? ' – Lớp '.$charge->languageClass->code : '' }}</td></tr></table>
<div class="amount-box"><div class="amount-line"><span>Số tiền:</span><strong>{{ number_format($totalAmount,0,',','.') }} đồng</strong></div><div class="words">Bằng chữ: {{ $amountInWords }}.</div></div>
@php($methods=['cash'=>'Tiền mặt','transfer'=>'Chuyển khoản','card'=>'Thẻ','other'=>'Khác'])
<table class="detail"><thead><tr><th>Nội dung</th><th>Học phí gốc</th><th>Miễn giảm</th><th>Phải thu</th><th>Thanh toán lần này</th></tr></thead><tbody><tr><td>{{ $charge->code }} · Học phí {{ $charge->course->name }}</td><td>{{ number_format($charge->original_amount,0,',','.') }}đ</td><td>{{ $charge->discount_percentage }}% ({{ number_format($charge->discount_amount,0,',','.') }}đ)</td><td>{{ number_format($charge->payable_amount,0,',','.') }}đ</td><td>{{ number_format($payment->amount,0,',','.') }}đ</td></tr>@if((float)$payment->book_amount>0)<tr><td>Giáo trình / sách</td><td>—</td><td>—</td><td>{{ number_format($payment->book_amount,0,',','.') }}đ</td><td>{{ number_format($payment->book_amount,0,',','.') }}đ</td></tr>@endif<tr><td colspan="4"><strong>TỔNG TIỀN CUỐI CÙNG</strong><div class="words">Bằng chữ: {{ $amountInWords }}.</div></td><td><strong>{{ number_format($totalAmount,0,',','.') }}đ</strong></td></tr></tbody></table>
<div class="note"><strong>Ghi chú:</strong> {{ $payment->note ?: $charge->note ?: 'Không' }}</div>
<div class="signatures"><div class="signature"><strong>Người nộp tiền</strong><small>(Ký, ghi rõ họ tên)</small><div class="signature-space"></div><span>{{ $student->name }}</span></div><div class="signature"><strong>Người lập phiếu</strong><small>(Ký, ghi rõ họ tên)</small><div class="signature-space"></div><span>{{ $payment->collector?->name ?: '........................' }}</span></div><div class="signature"><strong>Thủ quỹ</strong><small>(Ký, ghi rõ họ tên)</small><div class="signature-space"></div><span>........................</span></div></div>
<div class="footer">© 2026 <strong>E-sky center</strong> v1.0.0 | Phát triển bởi Đặng Việt Duy</div></div>
@if(!$pdfMode && $autoPrint)<script>window.addEventListener('load',()=>window.setTimeout(()=>window.print(),350));</script>@endif
</body></html>
