@extends('layouts.app')
@section('title','Hồ sơ '.$item->name)
@section('header','Quản lý học viên')
@section('content')
@php
$studentStatuses=['new'=>'Mới đăng ký','placement_test'=>'Chờ kiểm tra','waiting_class'=>'Chờ xếp lớp','studying'=>'Đang học','paused'=>'Tạm nghỉ','reserved'=>'Bảo lưu','completed'=>'Hoàn thành','dropped'=>'Thôi học'];
$enrollmentStatuses=['studying'=>'Đang học','paused'=>'Tạm nghỉ','reserved'=>'Bảo lưu','completed'=>'Hoàn thành','dropped'=>'Thôi học'];
$scoreTypes=['regular'=>'Thường xuyên','midterm'=>'Giữa kỳ','final'=>'Cuối kỳ','oral'=>'Vấn đáp','other'=>'Khác'];
$allScores=$item->enrollments->flatMap->scores;
$average=$allScores->count()?$allScores->avg(fn($score)=>(float)$score->score/(float)$score->max_score*10):null;
$tuitionPayable=(float)$item->tuitionCharges->sum('payable_amount');
$tuitionPaid=(float)$item->tuitionCharges->sum('paid_amount');
$tuitionRemaining=max(0,$tuitionPayable-$tuitionPaid);
$tuitionLabels=['unpaid'=>'Chưa đóng','partial'=>'Đóng một phần','pending_receipt'=>'Chờ phiếu thu','paid'=>'Đã đóng đủ'];
$paymentMethods=['cash'=>'Tiền mặt','transfer'=>'Chuyển khoản','card'=>'Thẻ','other'=>'Khác'];
@endphp
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="page-title">{{$item->code}} – {{$item->name}}</h1><div class="page-subtitle">Hồ sơ cá nhân, lịch sử lớp học, điểm kiểm tra và đánh giá quá trình.</div></div><div class="d-flex gap-2"><a class="btn btn-light" href="{{route('language-students.index')}}"><i class="bi bi-arrow-left me-2"></i>Danh sách</a>@if(auth()->user()->allowed('language_students','update'))<a class="btn btn-primary" href="{{route('language-students.edit',$item)}}"><i class="bi bi-pencil me-2"></i>Chỉnh sửa</a>@endif</div></div>

<div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><div class="card card-soft h-100"><div class="card-body p-4"><div class="stat-label">Trạng thái</div><div class="fs-5 fw-bold mt-2">{{$studentStatuses[$item->status]??$item->status}}</div></div></div></div><div class="col-sm-6 col-xl-3"><div class="card card-soft h-100"><div class="card-body p-4"><div class="stat-label">Số lớp đã học</div><div class="stat-value">{{$item->enrollments->count()}}</div></div></div></div><div class="col-sm-6 col-xl-3"><div class="card card-soft h-100"><div class="card-body p-4"><div class="stat-label">Số bài kiểm tra</div><div class="stat-value">{{$allScores->count()}}</div></div></div></div><div class="col-sm-6 col-xl-3"><div class="card card-soft h-100"><div class="card-body p-4"><div class="stat-label">Điểm trung bình quy đổi</div><div class="stat-value text-primary">{{$average!==null?number_format($average,1).'/10':'—'}}</div></div></div></div></div>

<div class="card card-soft mb-4"><div class="card-header bg-white p-4"><h5 class="mb-0"><i class="bi bi-person-vcard me-2"></i>Thông tin học viên</h5></div><div class="card-body p-4"><div class="row g-3"><div class="col-md-4"><span class="text-muted">Ngày sinh</span><strong class="d-block">{{$item->date_of_birth?->format('d/m/Y')?:'Chưa cập nhật'}}</strong></div><div class="col-md-4"><span class="text-muted">Điện thoại</span><strong class="d-block">{{$item->phone?:'Chưa cập nhật'}}</strong></div><div class="col-md-4"><span class="text-muted">Email</span><strong class="d-block">{{$item->email?:'Chưa cập nhật'}}</strong></div><div class="col-md-4"><span class="text-muted">Trường/lớp</span><strong class="d-block">{{trim(($item->school?:'').' '.($item->school_class?:''))?:'Chưa cập nhật'}}</strong></div><div class="col-md-4"><span class="text-muted">Khóa học</span><strong class="d-block">{{$item->course?->name?:'Chưa chọn'}}</strong></div><div class="col-md-4"><span class="text-muted">Ngày nhập học</span><strong class="d-block">{{$item->official_enrollment_date?->format('d/m/Y')?:'Chưa nhập học'}}</strong></div><div class="col-12"><span class="text-muted">Phụ huynh/người giám hộ</span><div>@forelse($item->guardians as $guardian)<span class="badge bg-light text-dark border me-2">{{$guardian->name}} · {{$guardian->phone}}</span>@empty Chưa cập nhật @endforelse</div></div></div></div></div>

<div class="card card-soft mb-4"><div class="card-header bg-white p-4 d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="mb-1"><i class="bi bi-cash-coin me-2 text-success"></i>Tình hình đóng học phí</h5><div class="small text-muted">Tự động cập nhật từ các phiếu thu của học viên.</div></div>@if(auth()->user()->allowed('language_tuition','create'))<a class="btn btn-sm btn-outline-success" href="{{route('language-tuition.create',['student'=>$item->id,'course'=>$item->language_course_id])}}"><i class="bi bi-plus-circle me-1"></i>Lập khoản thu</a>@endif</div><div class="card-body p-4"><div class="row g-3"><div class="col-md-4"><div class="tuition-student-summary"><span>Tổng phải đóng</span><strong>{{number_format($tuitionPayable)}}đ</strong></div></div><div class="col-md-4"><div class="tuition-student-summary paid"><span>Đã đóng</span><strong>{{number_format($tuitionPaid)}}đ</strong></div></div><div class="col-md-4"><div class="tuition-student-summary {{$tuitionRemaining>0?'due':'complete'}}"><span>Còn phải đóng</span><strong>{{number_format($tuitionRemaining)}}đ</strong></div></div></div>@if($item->tuitionCharges->isEmpty())<div class="alert alert-light border mt-3 mb-0">Học viên chưa được lập khoản thu học phí.</div>@elseif($tuitionRemaining<=0)<div class="alert alert-success mt-3 mb-0"><i class="bi bi-check-circle-fill me-2"></i>Học viên đã hoàn thành toàn bộ học phí đã lập.</div>@endif</div></div>

@if($item->tuitionCharges->isNotEmpty())
<div class="card card-soft mb-4"><div class="card-header bg-white p-4"><h5 class="mb-1">Chi tiết khoản thu và các lần đóng tiền</h5><div class="small text-muted">Bao gồm cả khoản thu chưa gắn lớp.</div></div><div class="table-responsive"><table class="table table-modern mb-0"><thead><tr><th>Khoản thu</th><th>Khóa học / lớp</th><th>Phải đóng</th><th>Đã đóng</th><th>Còn lại</th><th>Trạng thái</th><th>Lần đóng gần nhất</th><th></th></tr></thead><tbody>@foreach($item->tuitionCharges as $charge)@php($remaining=max(0,(float)$charge->payable_amount-(float)$charge->paid_amount))@php($latestPayment=$charge->payments->sortByDesc('paid_at')->first())<tr><td><strong>{{$charge->code}}</strong><div class="small text-muted">{{$charge->created_at?->format('d/m/Y')}}</div></td><td>{{$charge->course?->name}}<div class="small text-muted">{{$charge->languageClass?->code?:'Chưa gắn lớp'}}</div></td><td>{{number_format($charge->payable_amount)}}đ</td><td class="fw-bold text-success">{{number_format($charge->paid_amount)}}đ</td><td class="fw-bold {{$remaining>0?'text-danger':'text-muted'}}">{{number_format($remaining)}}đ</td><td><span class="badge-soft {{$charge->status==='paid'?'badge-success':(in_array($charge->status,['partial','pending_receipt'])?'badge-warning':'badge-danger')}}">{{$tuitionLabels[$charge->status]??$charge->status}}</span></td><td>@if($latestPayment){{$latestPayment->paid_at?->format('d/m/Y')}}<div class="small text-muted">{{number_format((float)$latestPayment->amount+(float)$latestPayment->book_amount)}}đ · {{$paymentMethods[$latestPayment->payment_method]??$latestPayment->payment_method}}</div>@else<span class="text-muted">Chưa đóng</span>@endif</td><td>@if(auth()->user()->allowed('language_tuition'))<a class="btn btn-sm btn-outline-success" href="{{route('language-tuition.show',$charge)}}"><i class="bi bi-eye"></i></a>@endif</td></tr>@endforeach</tbody></table></div></div>
@endif

<div class="d-flex justify-content-between align-items-end mb-3"><div><h4 class="mb-1">Các lớp đã tham gia</h4><div class="text-muted">Chọn một thẻ lớp để xem học phí, điểm và đánh giá chi tiết.</div></div></div>
@if($item->enrollments->isEmpty())
<div class="card card-soft"><div class="empty-state">Học viên chưa có lịch sử lớp học.</div></div>
@else
<div class="row g-3 mb-4 student-class-grid">
@foreach($item->enrollments as $enrollment)
@php($class=$enrollment->languageClass)
@php($classAverage=$enrollment->scores->count()?$enrollment->scores->avg(fn($score)=>(float)$score->score/(float)$score->max_score*10):null)
@php($classCharges=$item->tuitionCharges->where('language_class_id',$class?->id))
@php($classDue=max(0,(float)$classCharges->sum('payable_amount')-(float)$classCharges->sum('paid_amount')))
<div class="col-sm-6 col-lg-4 col-xxl-3"><button class="student-class-tile collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#student-class-detail-{{$enrollment->id}}" aria-expanded="false" aria-controls="student-class-detail-{{$enrollment->id}}"><span class="student-class-icon"><i class="bi bi-easel2-fill"></i></span><span class="student-class-code">{{$class?->code?:'Lớp không còn hoạt động'}}</span><strong>{{$class?->name?:'Thông tin lớp cũ'}}</strong><small>{{$class?->program?->name}} · {{$class?->level?->name}}</small><span class="student-class-meta"><span class="badge-soft {{$enrollment->status==='studying'?'badge-success':'badge-gray'}}">{{$enrollmentStatuses[$enrollment->status]??$enrollment->status}}</span><span>{{$enrollment->scores->count()}} bài · {{$classAverage!==null?'TB '.number_format($classAverage,1):'Chưa có điểm'}}</span></span><span class="student-class-tuition {{$classCharges->isNotEmpty()&&$classDue<=0?'is-paid':'is-due'}}"><i class="bi bi-cash-coin"></i> {{$classCharges->isEmpty()?'Chưa lập học phí':($classDue<=0?'Đã đóng đủ':'Còn '.number_format($classDue).'đ')}}</span><span class="student-class-period">{{$enrollment->enrolled_at?->format('d/m/Y')}} – {{$enrollment->ended_at?->format('d/m/Y')?:'Hiện tại'}}</span><span class="student-class-open"><i class="bi bi-chevron-down"></i> Xem chi tiết</span></button></div>
@endforeach
</div>

<div class="student-class-details" id="student-class-details">
@foreach($item->enrollments as $enrollment)
@php($class=$enrollment->languageClass)
@php($classCharges=$item->tuitionCharges->where('language_class_id',$class?->id))
<div class="collapse" id="student-class-detail-{{$enrollment->id}}" data-bs-parent="#student-class-details"><div class="card card-soft mb-4"><div class="card-header bg-white p-4 d-flex flex-wrap justify-content-between gap-2"><div><h5 class="mb-1">{{$class?->code}} – {{$class?->name}}</h5><div class="text-muted">{{$class?->program?->name}} · {{$class?->level?->name}} · GV: {{$class?->teacher?->name?:'Chưa phân công'}}</div></div><button class="btn btn-sm btn-light" type="button" data-bs-toggle="collapse" data-bs-target="#student-class-detail-{{$enrollment->id}}"><i class="bi bi-x-lg me-1"></i>Đóng</button></div>
<div class="card-body p-4"><h6 class="fw-bold mb-3"><i class="bi bi-wallet2 me-2 text-success"></i>Học phí của lớp này</h6><div class="table-responsive mb-4"><table class="table table-modern"><thead><tr><th>Mã khoản thu</th><th>Phải đóng</th><th>Đã đóng</th><th>Còn lại</th><th>Trạng thái</th><th></th></tr></thead><tbody>@forelse($classCharges as $charge)@php($remaining=max(0,(float)$charge->payable_amount-(float)$charge->paid_amount))<tr><td><strong>{{$charge->code}}</strong><div class="small text-muted">{{$charge->course?->name}}</div></td><td>{{number_format($charge->payable_amount)}}đ</td><td class="fw-bold text-success">{{number_format($charge->paid_amount)}}đ</td><td class="fw-bold {{$remaining>0?'text-danger':'text-muted'}}">{{number_format($remaining)}}đ</td><td><span class="badge-soft {{$charge->status==='paid'?'badge-success':(in_array($charge->status,['partial','pending_receipt'])?'badge-warning':'badge-danger')}}">{{$tuitionLabels[$charge->status]??$charge->status}}</span></td><td>@if(auth()->user()->allowed('language_tuition'))<a class="btn btn-sm btn-outline-success" href="{{route('language-tuition.show',$charge)}}"><i class="bi bi-eye me-1"></i>Phiếu thu</a>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">Chưa có khoản thu gắn với lớp này.</td></tr>@endforelse</tbody></table></div>
@if($classCharges->isNotEmpty())<h6 class="fw-bold mb-3">Lịch sử các lần đóng tiền</h6><div class="table-responsive mb-4"><table class="table table-modern"><thead><tr><th>Ngày đóng</th><th>Số phiếu</th><th>Số tiền</th><th>Hình thức</th><th>Người thu</th><th>Trạng thái phiếu</th></tr></thead><tbody>@forelse($classCharges->flatMap->payments->sortByDesc('paid_at') as $payment)<tr><td>{{$payment->paid_at?->format('d/m/Y H:i')}}</td><td>{{$payment->receipt_code?:'Chưa bổ sung'}}</td><td><strong>{{number_format((float)$payment->amount+(float)$payment->book_amount)}}đ</strong></td><td>{{$paymentMethods[$payment->payment_method]??$payment->payment_method}}</td><td>{{$payment->collector?->name?:'—'}}</td><td>{{$payment->receipt_status==='confirmed'?'Đã xác nhận':'Chờ phiếu'}}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">Chưa có lần đóng tiền.</td></tr>@endforelse</tbody></table></div>@endif
<h6 class="fw-bold mb-3">Điểm kiểm tra của học viên trong lớp này</h6><div class="table-responsive mb-4"><table class="table table-modern"><thead><tr><th>Ngày</th><th>Bài kiểm tra</th><th>Loại</th><th>Điểm</th><th>Quy đổi /10</th><th>Giáo viên</th><th>Ghi chú</th></tr></thead><tbody>@forelse($enrollment->scores as $score)<tr><td>{{$score->test_date->format('d/m/Y')}}</td><td><strong>{{$score->test_name}}</strong></td><td>{{$scoreTypes[$score->test_type]??$score->test_type}}</td><td>{{$score->score}}/{{$score->max_score}}</td><td class="fw-bold text-primary">{{number_format((float)$score->score/(float)$score->max_score*10,1)}}</td><td>{{$score->teacher?->name?:'—'}}</td><td>{{$score->note?:'—'}}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">Học viên chưa có điểm kiểm tra trong lớp này.</td></tr>@endforelse</tbody></table></div>
<h6 class="fw-bold mb-3">Đánh giá quá trình theo tháng</h6><div class="table-responsive"><table class="table table-modern"><thead><tr><th>Tháng</th><th>Chuyên cần</th><th>Tham gia</th><th>Bài tập</th><th>Đánh giá</th><th>Ghi chú</th><th>Giáo viên</th></tr></thead><tbody>@forelse($enrollment->monthlyProgress as $progress)<tr><td><strong>{{$progress->month->format('m/Y')}}</strong></td><td>{{$progress->attended_sessions}}/{{$progress->planned_sessions}} buổi</td><td>{{$progress->participation_score!==null?$progress->participation_score.'/10':'—'}}</td><td>{{$progress->homework_score!==null?$progress->homework_score.'/10':'—'}}</td><td>{{$progress->assessment?:'—'}}</td><td>{{$progress->learning_note?:'—'}}</td><td>{{$progress->teacher?->name?:'—'}}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">Chưa có đánh giá quá trình theo tháng.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endforeach
</div>
@endif
@endsection
