@extends('layouts.app')
@section('title','Gửi chỉ tiêu')
@section('header','Tư vấn tuyển sinh')
@section('content')
@php($statusLabels=['new'=>'Mới tiếp nhận','contacted'=>'Đã liên hệ','consulting'=>'Đang tư vấn','placement_test'=>'Hẹn kiểm tra','waiting'=>'Chờ phản hồi','registered'=>'Đã đăng ký','not_interested'=>'Không quan tâm','follow_up'=>'Chăm sóc lại'])
@php($consultedCount=$items->getCollection()->filter(fn($item)=>$item->lead&&($item->lead->last_consulted_at||$item->lead->status!=='new'))->count())
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><h1 class="page-title">Gửi chỉ tiêu</h1><div class="page-subtitle">Gửi thông tin khách hàng và khóa học quan tâm cho bộ phận tư vấn.</div></div>
    <button class="btn btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#mySubmissionHistory" aria-expanded="false"><i class="bi bi-clock-history"></i>Xem lịch sử của tôi <span class="badge text-bg-primary">{{$items->total()}}</span></button>
</div>
@if($consultedCount)<div class="alert alert-info border-0 shadow-sm" data-auto-dismiss="5000"><i class="bi bi-bell-fill me-2"></i><strong>{{$consultedCount}} khách hàng</strong> bạn gửi đã được nhân viên tư vấn cập nhật.</div>@endif

<div class="row justify-content-center"><div class="col-xl-7 col-lg-9"><div class="card card-soft form-card"><div class="card-header"><h5><i class="bi bi-send-fill me-2"></i>Thông tin gửi</h5></div><div class="card-body p-4">
<form method="POST" action="{{route('language-target-submissions.store')}}" data-target-submission-form>@csrf
    <div class="row g-3"><div class="col-md-6"><label class="form-label required-label">Họ và tên</label><input class="form-control" name="name" value="{{old('name')}}" required></div><div class="col-md-6"><label class="form-label required-label">Số điện thoại</label><input class="form-control" name="phone" value="{{old('phone')}}" required></div></div>
    <div class="mt-3"><label class="form-label required-label">Khóa học quan tâm</label><select class="form-select" name="language_course_id" data-course-select data-searchable-select data-search-placeholder="Tìm tên khóa học, giáo trình..."><option value="">Chọn khóa học</option>@foreach($courses as $course)<option value="{{$course->id}}" @selected(old('language_course_id')==$course->id)>{{$course->name}} · {{$course->textbook?:'Chưa có giáo trình'}}</option>@endforeach<option value="__other__" @selected(old('course_choice')==='other')>Khác – Nhập khóa học quan tâm</option></select></div>
    <input type="hidden" name="course_choice" value="{{old('course_choice','existing')}}" data-course-choice>
    <div class="mt-3 {{old('course_choice')==='other'?'':'d-none'}}" data-other-course-box><label class="form-label required-label">Khóa học quan tâm khác</label><input class="form-control" name="other_course" value="{{old('other_course')}}" placeholder="Nhập tên khóa học quan tâm" data-other-course></div>
    <button class="btn btn-primary w-100 mt-4"><i class="bi bi-send"></i>Gửi chỉ tiêu</button>
</form></div></div></div></div>

<div class="collapse mt-4" id="mySubmissionHistory"><div class="card card-soft"><div class="card-header d-flex justify-content-between align-items-center"><h5 class="mb-0"><i class="bi bi-clock-history me-2"></i>Lịch sử của tôi</h5><button class="btn btn-sm btn-light" type="button" data-bs-toggle="collapse" data-bs-target="#mySubmissionHistory" title="Ẩn lịch sử"><i class="bi bi-chevron-up"></i></button></div><div class="table-responsive"><table class="table table-modern"><thead><tr><th>Người quan tâm</th><th>Khóa học</th><th>Trạng thái</th><th>Thời gian</th><th></th></tr></thead><tbody>
@forelse($items as $item) @php($consulted=$item->lead&&($item->lead->last_consulted_at||$item->lead->status!=='new'))
<tr><td><strong>{{$item->name}}</strong><div class="small text-muted">{{$item->phone}}</div></td><td><span class="d-inline-block text-truncate" style="max-width:220px" title="{{$item->course?->name?:$item->other_course}}">{{$item->course?->name?:$item->other_course}}</span></td><td>@if(!$item->lead)<span class="badge-soft badge-warning">Chờ đồng bộ</span>@elseif($consulted)<span class="badge-soft badge-success">{{$statusLabels[$item->lead->status]??$item->lead->status}}</span>@else<span class="badge-soft badge-info">Mới tiếp nhận</span>@endif</td><td class="text-nowrap">{{$item->created_at?->format('d/m/Y H:i')}}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#submissionDetail{{$item->id}}" title="Xem chi tiết"><i class="bi bi-eye"></i></button></td></tr>
@empty<tr><td colspan="5"><div class="empty-state">Bạn chưa gửi chỉ tiêu nào.</div></td></tr>@endforelse
</tbody></table></div><div class="card-footer bg-white border-0">{{$items->links()}}</div></div></div>

@foreach($items as $item)
<div class="modal fade" id="submissionDetail{{$item->id}}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow"><div class="modal-header"><h5 class="modal-title"><i class="bi bi-info-circle me-2"></i>Chi tiết lượt gửi</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><div class="small text-muted">Khách hàng</div><strong>{{$item->name}}</strong> · {{$item->phone}}</div><div class="col-12"><div class="small text-muted">Khóa học quan tâm</div><strong>{{$item->course?->name?:$item->other_course}}</strong></div><div class="col-md-6"><div class="small text-muted">Tư vấn viên</div><strong>{{$item->lead?->consultant?->name?:'Chưa phân công'}}</strong></div><div class="col-md-6"><div class="small text-muted">Trạng thái</div><span class="badge-soft {{$item->lead&&$item->lead->status!=='new'?'badge-success':'badge-info'}}">{{$item->lead?($statusLabels[$item->lead->status]??$item->lead->status):'Chờ đồng bộ'}}</span></div><div class="col-12"><div class="small text-muted">Thời gian gửi</div><strong>{{$item->created_at?->format('d/m/Y H:i')}}</strong></div>@if($item->lead?->last_consulted_at)<div class="col-12"><div class="small text-muted">Tư vấn gần nhất</div><strong>{{$item->lead->last_consulted_at->format('d/m/Y H:i')}}</strong></div>@endif</div></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Đóng</button></div></div></div></div>
@endforeach
@endsection
@push('scripts')<script>document.querySelectorAll('[data-target-submission-form]').forEach(form=>{const select=form.querySelector('[data-course-select]'),choice=form.querySelector('[data-course-choice]'),box=form.querySelector('[data-other-course-box]'),other=form.querySelector('[data-other-course]');const update=()=>{const isOther=select.value==='__other__';choice.value=isOther?'other':'existing';box.classList.toggle('d-none',!isOther);other.required=isOther;if(isOther)select.removeAttribute('name');else select.setAttribute('name','language_course_id')};select.addEventListener('change',update);update()});</script>@endpush
