@extends('layouts.app')
@section('title','Công việc tư vấn') @section('header','Tư vấn tuyển sinh') @section('content')
@php($labels=['new'=>'Mới tiếp nhận','contacted'=>'Đã liên hệ','consulting'=>'Đang tư vấn','placement_test'=>'Hẹn kiểm tra','waiting'=>'Chờ phản hồi','follow_up'=>'Chăm sóc lại'])
@php($colors=['new'=>'info','contacted'=>'primary','consulting'=>'warning','placement_test'=>'primary','waiting'=>'gray','follow_up'=>'warning'])
@php($rows=['new'=>'consulting-row-new','contacted'=>'consulting-row-contacted','consulting'=>'consulting-row-consulting','placement_test'=>'consulting-row-test','waiting'=>'consulting-row-waiting','follow_up'=>'consulting-row-followup'])
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="page-title">{{$canViewAll?'Công việc tư vấn toàn trung tâm':'Công việc tư vấn của tôi'}}</h1><div class="page-subtitle">Học viên tiềm năng mới gửi hiển thị trước; quá 3 ngày chưa tư vấn được cảnh báo đỏ.</div></div><div class="d-flex flex-wrap align-items-center gap-2"><div class="consulting-pending-total"><span>Tổng số lượng còn chờ</span><strong>{{number_format($pendingCount)}}</strong></div>@if(auth()->user()->allowed('language_leads','create'))<a class="btn btn-primary" href="{{route('language-leads.create')}}"><i class="bi bi-person-plus me-1"></i>Thêm học viên</a>@endif</div></div>
<form class="filter-panel row g-3 mb-4"><div class="col-lg-3"><select class="form-select" name="status"><option value="">Mọi trạng thái</option>@foreach($labels as $key=>$label)<option value="{{$key}}" @selected(request('status')===$key)>{{$label}}</option>@endforeach</select></div><div class="col-lg-3"><input class="form-control" type="date" name="date" value="{{request('date')}}"></div><div class="col-lg-2"><select class="form-select" name="month"><option value="">Mọi tháng</option>@for($month=1;$month<=12;$month++)<option value="{{$month}}" @selected(request('month')==$month)>Tháng {{$month}}</option>@endfor</select></div><div class="col-lg-2"><input class="form-control" type="number" name="year" value="{{request('year')}}" placeholder="Năm"></div><div class="col-lg-2"><button class="btn btn-primary w-100"><i class="bi bi-filter"></i>Lọc</button></div></form>
<div class="d-flex flex-wrap gap-3 small mb-3"><span><i class="consulting-dot bg-info"></i>Mới tiếp nhận</span><span><i class="consulting-dot bg-primary"></i>Đã liên hệ / hẹn kiểm tra</span><span><i class="consulting-dot bg-warning"></i>Đang tư vấn / chăm sóc</span><span><i class="consulting-dot bg-secondary"></i>Chờ phản hồi</span><span><i class="consulting-dot bg-danger"></i>Quá hạn</span></div>
<div class="card card-soft"><div class="table-responsive"><table class="table table-modern"><thead><tr><th>STT</th><th>Học viên tiềm năng</th><th>Ngày nhập</th><th>Khóa học quan tâm</th><th>Nguồn & ghi chú</th><th>Lần tư vấn gần nhất</th><th>Trạng thái</th><th>Cảnh báo</th><th></th></tr></thead><tbody>
@forelse($items as $item) @php($last=$item->last_consulted_at??$item->created_at) @php($overdue=$last&&$last->lt(now()->subDays(3)))
<tr class="{{$overdue?'table-danger':($rows[$item->status]??'')}}"><td class="fw-bold text-muted">{{($items->firstItem()??1)+$loop->index}}</td><td><strong>{{$item->name}}</strong><div class="small text-muted">{{$item->code}} · {{$item->phone}}@if($canViewAll) · TV: {{$item->consultant?->name?:'Chưa phân công'}}@endif</div></td><td class="text-nowrap">{{$item->received_at?->format('d/m/Y')?:$item->created_at?->format('d/m/Y')}}</td><td>{{$item->course?->name??$item->program?->name??$item->targetSubmissions->first()?->other_course??'—'}}</td><td style="min-width:220px">@if($item->source)<strong>{{$item->source}}</strong>@endif @if($item->note)<div class="small text-muted {{$item->source?'mt-1':''}} text-wrap">{!!nl2br(e($item->note))!!}</div>@elseif(!$item->source)<span class="text-muted">—</span>@endif</td><td class="text-nowrap">{{$last?->format('d/m/Y H:i')}}</td><td><span class="badge-soft badge-{{$colors[$item->status]??'info'}}">{{$labels[$item->status]??$item->status}}</span></td><td>@if($overdue)<span class="badge bg-danger">Quá 3 ngày chưa tư vấn</span>@else<span class="text-success text-nowrap"><i class="bi bi-check-circle me-1"></i>Trong hạn</span>@endif</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-secondary" href="{{route('language-leads.show',$item)}}" title="Xem chi tiết"><i class="bi bi-eye"></i></a><a class="btn btn-sm btn-primary" href="{{route('language-leads.edit',$item)}}" title="Tư vấn"><i class="bi bi-headset"></i></a></td></tr>
@empty<tr><td colspan="9"><div class="empty-state">Không có học viên tiềm năng đang chờ tư vấn.</div></td></tr>@endforelse
</tbody></table></div><div class="card-footer bg-white border-0 d-flex justify-content-between align-items-center"><small class="text-muted">Hiển thị {{$items->firstItem()??0}}–{{$items->lastItem()??0}} / {{$items->total()}}</small>{{$items->links()}}</div></div>
@endsection
