@extends('layouts.app')
@section('title','Xem khách hàng') @section('header','Tư vấn tuyển sinh') @section('content')
@php($labels=['new'=>'Mới tiếp nhận','contacted'=>'Đã liên hệ','consulting'=>'Đang tư vấn','placement_test'=>'Hẹn kiểm tra','waiting'=>'Chờ phản hồi','registered'=>'Đã đăng ký','not_interested'=>'Không quan tâm','follow_up'=>'Chăm sóc lại'])
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="page-title">Thông tin khách hàng</h1><div class="page-subtitle">{{$item->code}} · Nhập vào ngày {{$item->received_at?->format('d/m/Y')?:$item->created_at?->format('d/m/Y')}}</div></div><div class="d-flex gap-2"><a class="btn btn-light" href="{{route('language-leads.index')}}"><i class="bi bi-arrow-left me-1"></i>Quay lại</a><a class="btn btn-primary" href="{{route('language-leads.edit',$item)}}"><i class="bi bi-pencil me-1"></i>Cập nhật / tư vấn</a></div></div>
<div class="row g-4"><div class="col-xl-7"><div class="card card-soft h-100"><div class="card-header"><h5><i class="bi bi-person-vcard me-2"></i>Hồ sơ khách hàng</h5></div><div class="card-body p-4"><div class="row g-4">
@foreach([['Họ tên',$item->name],['Điện thoại',$item->phone],['Email',$item->email?:'—'],['Zalo',$item->zalo?:'—'],['Ngày sinh',$item->date_of_birth?->format('d/m/Y')?:'—'],['Ngày nhập vào',$item->received_at?->format('d/m/Y')?:'—'],['Nguồn khách hàng',$item->source?:'—'],['Trạng thái',$labels[$item->status]??$item->status]] as [$label,$value])<div class="col-md-6"><div class="small text-muted mb-1">{{$label}}</div><div class="fw-semibold">{{$value}}</div></div>@endforeach
</div><hr><div class="small text-muted mb-1">Ghi chú</div><div>{!! nl2br(e($item->note?:'—')) !!}</div></div></div></div>
<div class="col-xl-5"><div class="card card-soft mb-4"><div class="card-header"><h5><i class="bi bi-book me-2"></i>Thông tin đăng ký</h5></div><div class="card-body p-4"><div class="mb-3"><div class="small text-muted">Khóa học quan tâm</div><strong>{{$item->course?->name?:'—'}}</strong></div><div class="mb-3"><div class="small text-muted">Chương trình</div><strong>{{$item->program?->name?:'—'}}</strong></div><div class="mb-3"><div class="small text-muted">Cộng tác viên giới thiệu</div><strong>{{$item->collaborator?->name?:'—'}}</strong><div class="small text-muted">{{$item->collaborator?->phone}}</div></div><div><div class="small text-muted">Tư vấn viên phụ trách</div><strong>{{$item->consultant?->name?:'Chưa phân công'}}</strong></div></div></div>
<div class="card card-soft"><div class="card-header"><h5><i class="bi bi-headset me-2"></i>Nội dung tư vấn</h5></div><div class="card-body p-4"><div class="small text-muted mb-2">Lần cập nhật tư vấn gần nhất: {{$item->last_consulted_at?->format('d/m/Y H:i')?:'Chưa tư vấn'}}</div><div>{!! nl2br(e($item->consultation?:'Chưa có nội dung tư vấn.')) !!}</div>@if($item->appointment_at)<hr><div><i class="bi bi-calendar-event me-2"></i>Lịch hẹn: <strong>{{$item->appointment_at->format('d/m/Y H:i')}}</strong></div>@endif</div></div></div></div>
@if($item->status==='registered' && !$item->converted_student_id)<div class="card card-soft mt-4"><div class="card-body d-flex justify-content-between align-items-center"><div><strong>Khách hàng đã đăng ký</strong><div class="small text-muted">Có thể chuyển hồ sơ này thành học viên.</div></div><form method="POST" action="{{route('language-leads.convert',$item)}}">@csrf<button class="btn btn-success" data-confirm="Tạo học viên và chuyển sang lập học phí?"><i class="bi bi-person-check me-2"></i>Chuyển thành học viên</button></form></div></div>@elseif($item->convertedStudent)<div class="alert alert-success mt-4"><i class="bi bi-check-circle me-2"></i>Đã chuyển thành học viên: <strong>{{$item->convertedStudent->code}} – {{$item->convertedStudent->name}}</strong></div>@endif
@endsection
