@extends('layouts.app')
@section('title','Sổ điểm '.$languageClass->code)
@section('header','Quản lý giảng dạy')
@section('content')
@php
$statusLabels=['studying'=>'Đang học','paused'=>'Tạm nghỉ','reserved'=>'Bảo lưu','completed'=>'Hoàn thành','dropped'=>'Thôi học'];
$scoreTypes=['regular'=>'Thường xuyên','midterm'=>'Giữa kỳ','final'=>'Cuối kỳ','oral'=>'Vấn đáp','other'=>'Khác'];
$activeCount=$languageClass->enrollments->where('status','studying')->count();
$monthScores=$languageClass->enrollments->flatMap->scores;
$monthAverage=$monthScores->count()?$monthScores->avg(fn($score)=>(float)$score->score/(float)$score->max_score*10):null;
@endphp
@unless(auth()->user()->isAdmin()||auth()->user()->allowed('language_classes','update'))
<style>.gradebook-toolbar form[action="{{route('teacher-classes.enrollments.store',$languageClass)}}"]{display:none}</style>
@endunless
@unless(auth()->user()->allowed('teacher_classes','update'))
<div class="alert alert-info"><i class="bi bi-eye me-2"></i>Bạn đang xem sổ điểm ở chế độ chỉ đọc.</div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.content form[method="POST"]').forEach(form=>{form.querySelectorAll('input,select,textarea,button').forEach(control=>control.disabled=true);form.querySelectorAll('button').forEach(button=>button.classList.add('d-none'))})});</script>@endpush
@endunless

<div class="card card-soft mb-4"><div class="card-body p-4"><div class="d-flex flex-wrap justify-content-between gap-3"><div><h5><i class="bi bi-clipboard-check me-2"></i>Hoàn thành và đóng lớp</h5>@if($languageClass->completion_requested_at)<p class="mb-0">Giáo viên đã gửi đề nghị lúc <strong>{{$languageClass->completion_requested_at->format('H:i d/m/Y')}}</strong>. {{$languageClass->completion_note}}</p>@else<p class="mb-0 text-muted">Giáo viên gửi đề nghị khi đủ số buổi hoặc đến ngày kết thúc; giáo vụ kiểm tra học phí rồi mới đóng lớp.</p>@endif</div><div>@if($languageClass->status!=='completed'&&!$languageClass->completion_requested_at)<form method="POST" action="{{route('teacher-classes.completion.request',$languageClass)}}">@csrf @method('PATCH')<button class="btn btn-primary" {{$languageClass->isCompletionDue()?'':'disabled'}}><i class="bi bi-send-check me-2"></i>Đề nghị hoàn thành</button></form>@elseif($languageClass->status!=='completed'&&(auth()->user()->isAdmin()||auth()->user()->allowed('language_classes','update')))<form method="POST" action="{{route('teacher-classes.close',$languageClass)}}">@csrf @method('PATCH')<button class="btn btn-success" {{$tuitionCheck['ready']?'':'disabled'}} data-confirm="Xác nhận đã kiểm tra học phí và đóng lớp?"><i class="bi bi-lock-fill me-2"></i>Giáo vụ đóng lớp</button></form>@elseif($languageClass->completion_requested_at)<span class="badge text-bg-warning">Đang chờ giáo vụ kiểm tra</span>@endif</div></div>@if($languageClass->completion_requested_at&&!$tuitionCheck['ready'])<div class="alert alert-warning mt-3 mb-0"><strong>Chưa thể đóng lớp vì học phí:</strong><ul class="mb-0 mt-2">@foreach($tuitionCheck['blockers'] as $blocker)<li>{{$blocker['student']}}: {{$blocker['reason']}}</li>@endforeach</ul></div>@elseif($languageClass->completion_requested_at&&$tuitionCheck['ready'])<div class="alert alert-success mt-3 mb-0">Đã kiểm tra {{$tuitionCheck['total']}} học viên: học phí đầy đủ, có thể đóng lớp.</div>@endif</div></div>

<div class="gradebook-hero mb-4"><div><a class="gradebook-back" href="{{route('teacher-classes.index')}}"><i class="bi bi-arrow-left"></i> Lớp giảng dạy</a><div class="d-flex flex-wrap align-items-center gap-3 mt-3"><span class="gradebook-class-icon"><i class="bi bi-easel2-fill"></i></span><div><h1>{{$languageClass->code}} – {{$languageClass->name}}</h1><p>{{$languageClass->program?->name}} · {{$languageClass->level?->name}} · {{$languageClass->schedule_note?:'Chưa có lịch học'}}</p></div></div></div><div class="gradebook-teacher"><span>Giáo viên phụ trách</span><strong>{{$languageClass->teacher?->name?:'Chưa phân công'}}</strong></div></div>

<div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="gradebook-stat"><i class="bi bi-people-fill text-primary"></i><div><span>Đang học</span><strong>{{$activeCount}}</strong></div></div></div><div class="col-6 col-xl-3"><div class="gradebook-stat"><i class="bi bi-journal-check text-success"></i><div><span>Bài kiểm tra tháng</span><strong>{{$monthScores->count()}}</strong></div></div></div><div class="col-6 col-xl-3"><div class="gradebook-stat"><i class="bi bi-star-fill text-warning"></i><div><span>Điểm TB tháng</span><strong>{{$monthAverage!==null?number_format($monthAverage,1):'—'}}</strong></div></div></div><div class="col-6 col-xl-3"><div class="gradebook-stat"><i class="bi bi-calendar3 text-info"></i><div><span>Tháng đang xem</span><strong>{{$month->format('m/Y')}}</strong></div></div></div></div>

<div class="card card-soft gradebook-toolbar mb-4"><div class="card-body p-4"><div class="row g-3 align-items-end"><div class="col-lg-3"><form class="d-flex gap-2 align-items-end"><div class="flex-grow-1"><label class="form-label fw-semibold">Tháng theo dõi</label><input class="form-control" type="month" name="month" value="{{$month->format('Y-m')}}"></div><button class="btn btn-primary"><i class="bi bi-arrow-repeat"></i></button></form></div><div class="col-lg-3"><form class="d-flex gap-2 align-items-end" method="POST" action="{{route('teacher-classes.sessions.update',$languageClass)}}">@csrf @method('PATCH')<div class="flex-grow-1"><label class="form-label fw-semibold">Số buổi đã học</label><input class="form-control" type="number" name="completed_sessions" min="0" value="{{$languageClass->completed_sessions}}" required></div><button class="btn btn-outline-success" title="Cập nhật số buổi"><i class="bi bi-check2"></i></button></form></div><div class="col-lg-6"><form class="row g-2" method="POST" action="{{route('teacher-classes.enrollments.store',$languageClass)}}">@csrf<div class="col-md-7"><label class="form-label fw-semibold">Xếp thêm học viên</label><select class="form-select" name="language_student_id" required><option value="">Chọn học viên chưa có trong lớp</option>@foreach($availableStudents as $student)<option value="{{$student->id}}">{{$student->code}} – {{$student->name}}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label fw-semibold">Ngày vào lớp</label><input class="form-control" type="date" name="enrolled_at" value="{{now()->format('Y-m-d')}}" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary w-100"><i class="bi bi-person-plus"></i></button></div></form></div></div><div class="small text-muted mt-3"><i class="bi bi-info-circle me-1"></i>Lớp tự kết thúc khi đạt {{$languageClass->expected_sessions}} buổi hoặc qua ngày {{$languageClass->expected_end_date?->format('d/m/Y')?:'chưa thiết lập'}}.</div></div></div>

<section class="mb-4"><div class="gradebook-section-heading"><div><span>01</span><div><h4>Đánh giá quá trình tháng {{$month->format('m/Y')}}</h4><p>Nhập nhanh trên một dòng cho mỗi học viên, sau đó lưu một lần.</p></div></div></div>
<form method="POST" action="{{route('teacher-classes.progress.update',$languageClass)}}">@csrf @method('PUT')<input type="hidden" name="month" value="{{$month->format('Y-m')}}"><div class="card card-soft overflow-hidden"><div class="table-responsive"><table class="table gradebook-progress-table mb-0"><thead><tr><th>Học viên</th><th class="text-center">Kế hoạch</th><th class="text-center">Tham gia</th><th class="text-center">Chuyên cần</th><th class="text-center">Tham gia /10</th><th class="text-center">Bài tập /10</th><th>Đánh giá ngắn</th><th>Ghi chú</th></tr></thead><tbody>
@forelse($languageClass->enrollments as $enrollment)
@php($progress=$enrollment->monthlyProgress->first())
@php($attendance=($progress?->planned_sessions??0)>0?round(($progress->attended_sessions/$progress->planned_sessions)*100):null)
<tr class="{{$enrollment->status!=='studying'?'is-inactive':''}}"><td class="gradebook-student-cell"><strong>{{$enrollment->student?->name}}</strong><small>{{$enrollment->student?->code}} · {{$statusLabels[$enrollment->status]??$enrollment->status}}</small></td><td><input class="form-control gradebook-number" type="number" min="0" max="100" name="progress[{{$enrollment->id}}][planned_sessions]" value="{{old('progress.'.$enrollment->id.'.planned_sessions',$progress?->planned_sessions)}}"></td><td><input class="form-control gradebook-number" type="number" min="0" max="100" name="progress[{{$enrollment->id}}][attended_sessions]" value="{{old('progress.'.$enrollment->id.'.attended_sessions',$progress?->attended_sessions)}}"></td><td class="text-center"><span class="gradebook-attendance {{$attendance!==null&&$attendance<70?'low':''}}">{{$attendance!==null?$attendance.'%':'—'}}</span></td><td><input class="form-control gradebook-number" type="number" step="0.01" min="0" max="10" name="progress[{{$enrollment->id}}][participation_score]" value="{{old('progress.'.$enrollment->id.'.participation_score',$progress?->participation_score)}}"></td><td><input class="form-control gradebook-number" type="number" step="0.01" min="0" max="10" name="progress[{{$enrollment->id}}][homework_score]" value="{{old('progress.'.$enrollment->id.'.homework_score',$progress?->homework_score)}}"></td><td><input class="form-control gradebook-text" name="progress[{{$enrollment->id}}][assessment]" value="{{old('progress.'.$enrollment->id.'.assessment',$progress?->assessment)}}" placeholder="Tiến bộ, thái độ..."></td><td><input class="form-control gradebook-text" name="progress[{{$enrollment->id}}][learning_note]" value="{{old('progress.'.$enrollment->id.'.learning_note',$progress?->learning_note)}}" placeholder="Nội dung cần lưu ý"></td></tr>
@empty<tr><td colspan="8"><div class="empty-state">Lớp chưa có học viên.</div></td></tr>@endforelse
</tbody></table></div>@if($languageClass->enrollments->isNotEmpty())<div class="gradebook-savebar"><div><i class="bi bi-info-circle me-1"></i>Dữ liệu được lưu riêng cho từng học viên trong tháng {{$month->format('m/Y')}}.</div><button class="btn btn-primary"><i class="bi bi-save me-2"></i>Lưu đánh giá tháng</button></div>@endif</div></form></section>

<section><div class="gradebook-section-heading"><div><span>02</span><div><h4>Điểm kiểm tra và trạng thái học</h4><p>Chọn một học viên để xem điểm, nhập bài kiểm tra hoặc cập nhật nghỉ học.</p></div></div></div>
<div class="accordion gradebook-accordion" id="student-score-accordion">
@forelse($languageClass->enrollments as $enrollment)
@php($studentScores=$enrollment->scores)
@php($studentAverage=$studentScores->count()?$studentScores->avg(fn($score)=>(float)$score->score/(float)$score->max_score*10):null)
<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#student-score-{{$enrollment->id}}"><span class="gradebook-student-avatar">{{mb_strtoupper(mb_substr($enrollment->student?->name?:'H',0,1))}}</span><span class="gradebook-accordion-name"><strong>{{$enrollment->student?->name}}</strong><small>{{$enrollment->student?->code}} · {{$statusLabels[$enrollment->status]??$enrollment->status}}</small></span><span class="gradebook-score-summary"><span>{{$studentScores->count()}} bài</span><strong>{{$studentAverage!==null?number_format($studentAverage,1).'/10':'Chưa có điểm'}}</strong></span></button></h2>
<div id="student-score-{{$enrollment->id}}" class="accordion-collapse collapse" data-bs-parent="#student-score-accordion"><div class="accordion-body p-4"><div class="row g-4"><div class="col-xl-8"><h6 class="gradebook-subtitle">Danh sách điểm tháng {{$month->format('m/Y')}}</h6><div class="table-responsive"><table class="table table-modern"><thead><tr><th>Ngày</th><th>Bài kiểm tra</th><th>Loại</th><th>Điểm</th><th>Quy đổi</th><th></th></tr></thead><tbody>@forelse($studentScores as $score)<tr><td>{{$score->test_date->format('d/m/Y')}}</td><td><strong>{{$score->test_name}}</strong><div class="small text-muted">{{$score->note}}</div></td><td>{{$scoreTypes[$score->test_type]??$score->test_type}}</td><td>{{$score->score}}/{{$score->max_score}}</td><td class="fw-bold text-primary">{{number_format((float)$score->score/(float)$score->max_score*10,1)}}/10</td><td><form method="POST" action="{{route('teacher-classes.scores.destroy',[$languageClass,$enrollment,$score])}}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" data-confirm="Xóa điểm kiểm tra này?"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Chưa có điểm trong tháng này.</td></tr>@endforelse</tbody></table></div></div>
<div class="col-xl-4"><div class="gradebook-score-form"><h6 class="gradebook-subtitle">Thêm điểm kiểm tra</h6><form method="POST" action="{{route('teacher-classes.scores.store',[$languageClass,$enrollment])}}">@csrf<div class="row g-2"><div class="col-6"><label class="form-label">Ngày</label><input class="form-control" type="date" name="test_date" value="{{now()->format('Y-m-d')}}" required></div><div class="col-6"><label class="form-label">Loại</label><select class="form-select" name="test_type">@foreach($scoreTypes as $key=>$label)<option value="{{$key}}">{{$label}}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Tên bài kiểm tra</label><input class="form-control" name="test_name" required placeholder="Ví dụ: Kiểm tra từ vựng"></div><div class="col-6"><label class="form-label">Điểm</label><input class="form-control" type="number" step="0.01" min="0" name="score" required></div><div class="col-6"><label class="form-label">Điểm tối đa</label><input class="form-control" type="number" step="0.01" min="0.01" name="max_score" value="10" required></div><div class="col-12"><label class="form-label">Ghi chú</label><input class="form-control" name="note"></div><div class="col-12"><button class="btn btn-primary w-100"><i class="bi bi-plus-circle me-2"></i>Thêm điểm</button></div></div></form></div></div></div>
<hr class="my-4"><form method="POST" action="{{route('teacher-classes.enrollments.status',[$languageClass,$enrollment])}}">@csrf @method('PATCH')<div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">Trạng thái học</label><select class="form-select" name="status">@foreach($statusLabels as $key=>$label)<option value="{{$key}}" @selected($enrollment->status===$key)>{{$label}}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Ngày kết thúc</label><input class="form-control" type="date" name="ended_at" value="{{$enrollment->ended_at?->format('Y-m-d')}}"></div><div class="col-md-4"><label class="form-label">Lý do nghỉ/bảo lưu</label><input class="form-control" name="exit_reason" value="{{$enrollment->exit_reason}}"></div><div class="col-md-2"><button class="btn btn-outline-secondary w-100"><i class="bi bi-check2 me-1"></i>Cập nhật</button></div></div></form></div></div></div>
@empty<div class="card card-soft"><div class="empty-state">Lớp chưa có học viên.</div></div>@endforelse
</div></section>
@endsection
