<?php
namespace App\Http\Controllers;
use App\Models\{LanguageClass,LanguageProgram,LanguageLevel,LanguageStudent,LanguageEnrollment,User}; use Illuminate\Http\{Request,RedirectResponse}; use Illuminate\Validation\Rule; use Illuminate\View\View;
class LanguageClassController extends Controller {
 public function index(Request $r):View{$q=LanguageClass::with(['program','level','teacher'])->withCount('enrollments')->latest();if($r->filled('q')){$s=$r->string('q');$q->where(fn($b)=>$b->where('name','like',"%$s%")->orWhere('code','like',"%$s%"));}if($r->filled('status'))$q->where('status',$r->status);return view('language.classes.index',['items'=>$q->paginate(\App\Support\Pagination::perPage())->withQueryString()]);}
 public function create():View{return $this->form(new LanguageClass);}
 public function store(Request $r):RedirectResponse{LanguageClass::create($this->data($r));return redirect()->route('language-classes.index')->with('success','Đã tạo lớp học.');}
 public function edit(LanguageClass $languageClass):View{return $this->form($languageClass->load('enrollments.student'));}
 public function update(Request $r,LanguageClass $languageClass):RedirectResponse{$languageClass->update($this->data($r,$languageClass));return redirect()->route('language-classes.index')->with('success','Đã cập nhật lớp học.');}
 public function destroy(LanguageClass $languageClass):RedirectResponse{$languageClass->delete();return back()->with('success','Đã xóa lớp học.');}
 public function enroll(Request $r,LanguageClass $languageClass):RedirectResponse{$d=$r->validate(['language_student_id'=>'required|exists:language_students,id','enrolled_at'=>'required|date','tuition'=>'required|numeric|min:0','discount'=>'nullable|numeric|min:0']);if($languageClass->enrollments()->count()>=$languageClass->max_students)return back()->withErrors(['class'=>'Lớp đã đủ sĩ số.']);$languageClass->enrollments()->updateOrCreate(['language_student_id'=>$d['language_student_id']],$d+['status'=>'studying']);return back()->with('success','Đã xếp học viên vào lớp.');}
 public function unenroll(LanguageClass $languageClass,LanguageEnrollment $enrollment):RedirectResponse{abort_unless($enrollment->language_class_id===$languageClass->id,404);$enrollment->delete();return back()->with('success','Đã đưa học viên khỏi lớp.');}
 private function form($item):View{return view('language.classes.form',compact('item')+['programs'=>LanguageProgram::where('active',1)->with('levels')->get(),'teachers'=>User::where('active',1)->orderBy('name')->get(),'students'=>LanguageStudent::whereIn('status',['new','waiting_class','studying'])->orderBy('name')->get()]);}
 private function data(Request $r,?LanguageClass $m=null):array{return $r->validate(['code'=>['required','max:30',Rule::unique('language_classes')->ignore($m)],'name'=>'required|max:255','language_program_id'=>'required|exists:language_programs,id','language_level_id'=>'nullable|exists:language_levels,id','teacher_user_id'=>'nullable|exists:users,id','room'=>'nullable|max:255','start_date'=>'nullable|date','expected_end_date'=>'nullable|date|after_or_equal:start_date','expected_sessions'=>'required|integer|min:0','max_students'=>'required|integer|min:1','default_tuition'=>'required|numeric|min:0','status'=>['required',Rule::in(['planned','recruiting','upcoming','active','paused','completed','cancelled'])],'schedule_note'=>'nullable','note'=>'nullable']);}
}
