@extends('layouts.app')
@section('title','Khóa học & quy đổi') @section('header','Quản lý khóa học')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="page-title">Khóa học & quy đổi KPI</h1><div class="page-subtitle">Cấu hình B1: đủ 2 lượt mới tính 1 KPI; các khóa khác có thể 1:1.</div></div>@if(auth()->user()->allowed('courses','create'))<a href="{{ route('courses.create') }}" class="btn btn-primary"><i class="bi bi-plus-circle me-2"></i>Thêm khóa học</a>@endif</div>
<form class="filter-panel row g-3 mb-4"><div class="col-md-7"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Tìm tên hoặc mã khóa học..."></div><div class="col-md-3"><select class="form-select" name="status"><option value="">Mọi trạng thái</option><option value="active" @selected(request('status')==='active')>Hoạt động</option><option value="locked" @selected(request('status')==='locked')>Đã khóa</option><option value="deleted" @selected(request('status')==='deleted')>Đã xóa</option></select></div><div class="col-md-2"><button class="btn btn-dark w-100">Lọc</button></div></form>
@if(auth()->user()->allowed('courses','delete'))<form id="bulk-courses" method="POST" action="{{ route('courses.bulk-destroy') }}" data-bulk-form="courses" data-bulk-confirm="Xóa các khóa học đã chọn?" class="mb-3 d-flex flex-wrap align-items-center gap-2">@csrf @method('DELETE')<label class="me-2"><input class="form-check-input me-1" type="checkbox" data-bulk-all="courses"> Chọn tất cả trang này</label><select class="form-select form-select-sm w-auto" name="delete_type"><option value="soft">Xóa mềm</option>@if(auth()->user()->isAdmin())<option value="force">Xóa vĩnh viễn</option>@endif</select><button class="btn btn-sm btn-outline-danger" data-bulk-submit disabled><i class="bi bi-trash me-1"></i>Xóa đã chọn (<span data-bulk-count>0</span>)</button></form>@endif
<div class="card card-soft"><div class="table-responsive"><table class="table table-modern">
<thead><tr><th>Khóa học</th><th>Nhóm</th><th>Quy đổi KPI</th><th>Thanh toán vượt</th><th>Trạng thái</th><th class="text-end">Thao tác</th></tr></thead>
<tbody>@forelse($courses as $c)<tr>
<td>@if(!$c->trashed() && auth()->user()->allowed('courses','delete'))<input class="form-check-input me-2" type="checkbox" name="ids[]" value="{{ $c->id }}" form="bulk-courses" data-bulk-item="courses">@endif<strong>{{ $c->name }}</strong><div class="small text-muted">{{ $c->code ?: 'Chưa có mã' }}</div></td>
<td>{{ $c->category ?: 'Khác' }}</td><td><span class="badge-soft badge-info">{{ $c->conversionText() }}</span></td><td>{{ number_format($c->default_excess_rate) }}đ/KPI</td>
<td>@if($c->trashed())<span class="badge-soft badge-danger">Đã xóa</span>@elseif($c->active)<span class="badge-soft badge-success">Hoạt động</span>@else<span class="badge-soft badge-warning">Đã khóa</span>@endif</td>
<td class="text-end">@if($c->trashed())<form class="d-inline" method="POST" action="{{ route('courses.restore',$c->id) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success">Khôi phục</button></form> @if(auth()->user()->isAdmin())<form class="d-inline" method="POST" action="{{ route('courses.force-destroy',$c->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-danger" data-confirm="Xóa vĩnh viễn khóa học khỏi database? Thao tác này không thể hoàn tác."><i class="bi bi-trash3 me-1"></i>Xóa vĩnh viễn</button></form>@endif @else @if(auth()->user()->allowed('courses','update'))<a class="btn btn-sm btn-outline-primary" href="{{ route('courses.edit',$c) }}"><i class="bi bi-pencil"></i></a><form class="d-inline" method="POST" action="{{ route('courses.toggle',$c) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-warning" data-confirm="Đổi trạng thái khóa học?"><i class="bi bi-lock"></i></button></form>@endif @if(auth()->user()->allowed('courses','delete'))<form class="d-inline" method="POST" action="{{ route('courses.destroy',$c) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" data-confirm="Xóa mềm khóa học?"><i class="bi bi-trash"></i></button></form>@endif @endif</td>
</tr>@empty<tr><td colspan="6"><div class="empty-state">Chưa có khóa học.</div></td></tr>@endforelse</tbody></table></div><div class="card-footer bg-white border-0 p-3">{{ $courses->links() }}</div></div>
@endsection
