@extends('layouts.app')
@section('title','Cấu hình phần mềm')
@section('header','Quản trị hệ thống')
@section('content')
@php($themes=[
'blue'=>['Xanh dương','#2563eb'],'navy'=>['Xanh navy','#163b72'],'indigo'=>['Chàm','#4f46e5'],'purple'=>['Tím','#7c3aed'],'pink'=>['Hồng','#d63384'],
'rose'=>['Hồng đỏ','#e11d48'],'red'=>['Đỏ','#dc3545'],'orange'=>['Cam','#ea580c'],'yellow'=>['Vàng','#d89b00'],'lime'=>['Xanh chanh','#65a30d'],
'green'=>['Xanh lá','#198754'],'teal'=>['Xanh ngọc','#0d9488'],'cyan'=>['Xanh cyan','#0891b2'],'brown'=>['Nâu','#92400e'],'slate'=>['Xám xanh','#475569']
])
<div class="page-toolbar d-flex justify-content-between mb-4"><div><h1 class="page-title">Cấu hình phần mềm</h1><div class="page-subtitle">Tùy chỉnh nhận diện thương hiệu và xem thay đổi ngay trước khi lưu.</div></div><span class="settings-status"><i class="bi bi-eye-fill"></i> Xem trước trực tiếp</span></div>
<form method="POST" action="{{ route('settings.theme.update') }}" enctype="multipart/form-data" data-branding-form data-original-theme="{{ $theme }}">@csrf @method('PUT')
<div class="row g-4">
<div class="col-xl-7"><div class="card card-soft form-card"><div class="card-header"><h5><i class="bi bi-building me-2"></i>Nhận diện thương hiệu</h5></div><div class="card-body p-4">
<div class="row g-4 align-items-start"><div class="col-md-7"><label class="form-label required-label" for="software_name">Tên phần mềm</label><input class="form-control @error('software_name') is-invalid @enderror" id="software_name" name="software_name" value="{{ old('software_name',$softwareName) }}" maxlength="80" required data-name-input><div class="form-text">Hiển thị trên tiêu đề trình duyệt, menu và trang đăng nhập.</div>@error('software_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-5"><label class="form-label">Logo hiện tại</label><div class="branding-logo-box" data-logo-preview>@if($logoPath)<img src="{{ asset($logoPath) }}?v={{ @filemtime(public_path($logoPath)) ?: time() }}" alt="Logo hiện tại">@else<i class="bi bi-mortarboard-fill"></i>@endif</div></div></div>
<div class="mt-4"><label class="form-label" for="logo">Tải logo mới</label><input class="form-control @error('logo') is-invalid @enderror" id="logo" type="file" name="logo" accept="image/png,image/jpeg,image/webp" data-logo-input>@error('logo')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">PNG, JPG hoặc WEBP; tối đa 2 MB. Logo luôn được đặt trên nền trắng để dễ nhìn.</div>@if($logoPath)<div class="form-check mt-3"><input class="form-check-input" type="checkbox" name="remove_logo" value="1" id="remove_logo"><label class="form-check-label" for="remove_logo">Xóa logo và dùng biểu tượng mặc định</label></div>@endif</div>
</div></div>
<div class="card card-soft form-card mt-4"><div class="card-header"><h5><i class="bi bi-palette me-2"></i>Bảng màu giao diện</h5></div><div class="card-body p-4"><p class="text-muted small mb-4">Bấm vào màu để áp dụng ngay trên trang này. Thay đổi chỉ được ghi nhận chính thức sau khi bấm “Lưu cấu hình”.</p><div class="theme-grid theme-grid-expanded">@foreach($themes as $key=>$option)<label class="theme-option @if(old('theme_color',$theme)===$key) selected @endif"><input type="radio" name="theme_color" value="{{ $key }}" @checked(old('theme_color',$theme)===$key)><span class="theme-swatch" style="--swatch:{{ $option[1] }}"></span><span><strong>{{ $option[0] }}</strong><small>{{ $option[1] }}</small></span><i class="bi bi-check-circle-fill"></i></label>@endforeach</div>@error('theme_color')<div class="text-danger small mt-2">{{ $message }}</div>@enderror</div></div></div>
<div class="card card-soft form-card mt-4"><div class="card-header"><h5><i class="bi bi-hourglass-split me-2"></i>Kiểu hiển thị khi tải</h5></div><div class="card-body p-4"><p class="text-muted small mb-3">Chọn cách thông báo khi hệ thống đang chuyển trang hoặc lưu dữ liệu.</p><div class="loading-style-grid">
<label class="loading-style-option @if(old('loading_style',$loadingStyle)==='center') selected @endif"><input type="radio" name="loading_style" value="center" @checked(old('loading_style',$loadingStyle)==='center')><span class="loading-demo center-demo"><i class="bi bi-arrow-repeat"></i></span><span><strong>Giữa màn hình</strong><small>Hộp loading nổi, khóa toàn bộ giao diện</small></span><i class="bi bi-check-circle-fill option-check"></i></label>
<label class="loading-style-option @if(old('loading_style',$loadingStyle)==='top') selected @endif"><input type="radio" name="loading_style" value="top" @checked(old('loading_style',$loadingStyle)==='top')><span class="loading-demo top-demo"><i></i></span><span><strong>Thanh tiến trình phía trên</strong><small>Gọn nhẹ, chạy sát cạnh trên màn hình</small></span><i class="bi bi-check-circle-fill option-check"></i></label>
</div>@error('loading_style')<div class="text-danger small mt-2">{{ $message }}</div>@enderror<button class="btn btn-outline-primary btn-sm mt-3" type="button" data-loading-preview><i class="bi bi-play-fill"></i>Xem thử kiểu loading</button></div></div>
<div class="card card-soft form-card mt-4"><div class="card-header"><h5><i class="bi bi-bank me-2"></i>Tài khoản ngân hàng thu học phí</h5></div><div class="card-body p-4">
<div class="bank-setting-toggle mb-4"><div><strong>Bật thanh toán chuyển khoản và VietQR</strong><small>Liên kết cấu hình này với trang Thu học phí.</small></div><div class="form-check form-switch"><input type="hidden" name="bank_enabled" value="0"><input class="form-check-input" type="checkbox" name="bank_enabled" value="1" id="bank_enabled" @checked(old('bank_enabled',$bankEnabled)) data-bank-enabled><label class="form-check-label" for="bank_enabled">Bật</label></div></div>
<div class="row g-3" data-bank-fields>
<div class="col-md-5"><label class="form-label">Mã BIN VietQR</label><input class="form-control @error('bank_bin') is-invalid @enderror" name="bank_bin" value="{{old('bank_bin',$bankBin)}}" inputmode="numeric" maxlength="6" list="bank-bin-list" placeholder="Ví dụ: 970428">@error('bank_bin')<div class="invalid-feedback">{{$message}}</div>@enderror<datalist id="bank-bin-list"><option value="970436">Vietcombank</option><option value="970415">VietinBank</option><option value="970418">BIDV</option><option value="970405">Agribank</option><option value="970422">MB Bank</option><option value="970407">Techcombank</option><option value="970416">ACB</option><option value="970432">VPBank</option><option value="970423">TPBank</option><option value="970403">Sacombank</option><option value="970428">Nam A Bank</option></datalist></div>
<div class="col-md-7"><label class="form-label">Tên ngân hàng</label><input class="form-control @error('bank_name') is-invalid @enderror" name="bank_name" value="{{old('bank_name',$bankName)}}" maxlength="100" placeholder="Ví dụ: Nam A Bank">@error('bank_name')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Số tài khoản</label><input class="form-control @error('bank_account_number') is-invalid @enderror" name="bank_account_number" value="{{old('bank_account_number',$bankAccountNumber)}}" inputmode="numeric" maxlength="30">@error('bank_account_number')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Chi nhánh</label><input class="form-control" name="bank_branch" value="{{old('bank_branch',$bankBranch)}}" maxlength="150" placeholder="Ví dụ: CN Cà Mau"></div>
<div class="col-12"><label class="form-label">Tên chủ tài khoản</label><input class="form-control text-uppercase @error('bank_account_name') is-invalid @enderror" name="bank_account_name" value="{{old('bank_account_name',$bankAccountName)}}" maxlength="150" placeholder="Tên không dấu theo ngân hàng">@error('bank_account_name')<div class="invalid-feedback">{{$message}}</div>@enderror<div class="form-text">Tên này được gửi sang VietQR và hiển thị tại trang thu học phí.</div></div>
</div></div></div>

<div class="col-xl-5"><div class="branding-preview-sticky"><div class="preview-heading"><div><strong>Xem trước giao diện</strong><small>Thay đổi theo lựa chọn của bạn</small></div><i class="bi bi-display"></i></div><div class="software-preview"><div class="preview-sidebar"><div class="preview-brand"><span data-preview-logo>@if($logoPath)<img src="{{ asset($logoPath) }}" alt="Logo">@else<i class="bi bi-mortarboard-fill"></i>@endif</span><strong data-preview-name>{{ old('software_name',$softwareName) }}</strong></div><div class="preview-nav active"><i class="bi bi-grid-fill"></i>Tổng quan</div><div class="preview-nav"><i class="bi bi-people"></i>Học viên</div><div class="preview-nav"><i class="bi bi-bar-chart"></i>Báo cáo</div></div><div class="preview-main"><div class="preview-topbar"><span></span><i class="bi bi-person-circle"></i></div><div class="preview-content"><div class="preview-title"></div><div class="preview-stats"><span></span><span></span><span></span></div><div class="preview-table"><i></i><i></i><i></i><i></i></div></div></div></div><div class="preview-note"><i class="bi bi-lightbulb-fill"></i><span>Màu, tên và logo phía trên là bản xem trước. Nhấn Lưu để áp dụng cho mọi người dùng.</span></div></div></div>
</div>
<div class="form-actions settings-actions"><a href="{{ route('dashboard') }}" class="btn btn-light">Hủy</a><button class="btn btn-primary" type="submit"><i class="bi bi-check2-circle"></i>Lưu cấu hình</button></div>
</form>
@endsection
@push('scripts')<script>
(()=>{const form=document.querySelector('[data-branding-form]');if(!form)return;const body=document.body,name=form.querySelector('[data-name-input]'),previewName=form.querySelector('[data-preview-name]'),file=form.querySelector('[data-logo-input]'),logoTargets=[form.querySelector('[data-logo-preview]'),form.querySelector('[data-preview-logo]')];form.querySelectorAll('.theme-option input').forEach(input=>input.addEventListener('change',()=>{body.dataset.theme=input.value;form.querySelectorAll('.theme-option').forEach(x=>x.classList.toggle('selected',x.contains(input)))}));name.addEventListener('input',()=>previewName.textContent=name.value.trim()||'Tên phần mềm');file.addEventListener('change',()=>{const selected=file.files?.[0];if(!selected)return;const url=URL.createObjectURL(selected);logoTargets.forEach(target=>{target.innerHTML='';const img=document.createElement('img');img.src=url;img.alt='Logo xem trước';target.appendChild(img)})});form.querySelectorAll('[name=loading_style]').forEach(input=>input.addEventListener('change',()=>{body.dataset.loadingStyle=input.value;form.querySelectorAll('.loading-style-option').forEach(x=>x.classList.toggle('selected',x.contains(input)))}));const bankToggle=form.querySelector('[data-bank-enabled]'),bankFields=form.querySelector('[data-bank-fields]');const syncBank=()=>bankFields?.classList.toggle('bank-disabled',!bankToggle?.checked);bankToggle?.addEventListener('change',syncBank);syncBank();form.querySelector('[data-loading-preview]')?.addEventListener('click',()=>{window.dispatchEvent(new Event('page-loading:show'));window.setTimeout(()=>window.dispatchEvent(new Event('page-loading:hide')),1300)})})();
</script>@endpush